# Юность. Студент {#cross}

Cross-references make it easier for your readers to find and link to elements in your book.

## 1970. Продолжение {#1970-2}

There are two steps to cross-reference any heading:

1. Label the heading: `# Hello world {#nice-label}`. 
    - Leave the label off if you like the automated heading generated based on your heading title: for example, `# Hello world` = `# Hello world {#hello-world}`.
    - To label an un-numbered heading, use: `# Hello world {-#nice-label}` or `{# Hello world .unnumbered}`.

1. Next, reference the labeled heading anywhere in the text using `\@ref(nice-label)`; for example, please see Chapter \@ref(cross). 
    - If you prefer text as the link instead of a numbered reference use: [any text you want can go here](#cross).

## 1971

Figures and tables *with captions* can also be cross-referenced from elsewhere in your book using `\@ref(fig:chunk-label)` and `\@ref(tab:chunk-label)`, respectively.

## 1972

1972

## 1973

1973

## 1974

1974

# Молодость {#molodost}

123

## 1975

1975

## 1976

1976

## 1977

1977

## 1978

1978

## 1979. Начало {#1979-1}

1979-1
