# Пожилой человек {#share}  

## 2011

HTML books can be published online, see: https://bookdown.org/yihui/bookdown/publishing.html

## 2012

By default, users will be directed to a 404 page if they try to access a webpage that cannot be found. If you'd like to customize your 404 page instead of using the default, you may add either a `_404.Rmd` or `_404.md` file to your project root and use code and/or Markdown syntax.

## 2013

Bookdown HTML books will provide HTML metadata for social sharing on platforms like Twitter, Facebook, and LinkedIn, using information you provide in the `index.Rmd` YAML. To setup, set the `url` for your book and the path to your `cover-image` file. Your book's `title` and `description` are also used.

## 2014

This `gitbook` uses the same social sharing data across all chapters in your book- all links shared will look the same.

## 2015

Specify your book's source repository on GitHub using the `edit` key under the configuration options in the `_output.yml` file, which allows users to suggest an edit by linking to a chapter's source file. 

## 2016

Read more about the features of this output format here:

## 2017

2017

## 2018

2018

## 2019

2019

## 2020

2020

## 2021

2021

## 2022

2022

## 2023

2023

## 2024

2024
